# Generated by Django 5.1.5 on 2025-02-13 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('include_confidence', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optional', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('demographics', 'Demographics'), ('presentation', 'Presentation'), ('symptoms', 'Signs and Symptoms'), ('imaging', 'Imaging'), ('workup', 'Workup'), ('intervention', 'Intervention'), ('postop', 'Immediate Post-op Outcomes'), ('followup', 'Follow-up'), ('lastfollowup', 'Last Follow-up')], default='demographics', max_length=50)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('include_confidence', models.BooleanField(default=True)),
                ('custom_prompt', models.TextField(blank=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.columndefinition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt_template', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('columns', models.ManyToManyField(through='core.JobColumnMapping', to='core.columndefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.processingjob')),
            ],
        ),
        migrations.AddField(
            model_name='jobcolumnmapping',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processingjob'),
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.pdfdocument')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variables', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='processingjob',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.savedprompt'),
        ),
        migrations.AlterUniqueTogether(
            name='jobcolumnmapping',
            unique_together={('job', 'column')},
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'created_at'], name='core_proces_status_c7a5c5_idx'),
        ),
    ]
