# Generated by Django 5.1.5 on 2025-02-13 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='raw_response',
            field=models.TextField(blank=True, help_text='Raw response from the AI model before JSON parsing', null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pdfdocument'),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='result_data',
            field=models.JSONField(default=dict),
        ),
    ]
