# Generated by Django 5.1.5 on 2025-02-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processingresult_raw_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columndefinition',
            name='data_type',
            field=models.CharField(choices=[('string', 'Text String'), ('integer', 'Integer Number'), ('float', 'Decimal Number'), ('date', 'Date'), ('boolean', 'True/False'), ('enum', 'Enumerated Values')], default='string', max_length=20),
        ),
        migrations.AddField(
            model_name='columndefinition',
            name='enum_values',
            field=models.JSONField(blank=True, help_text='List of allowed values for enum type', null=True),
        ),
        migrations.AddField(
            model_name='columndefinition',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Maximum value for numeric types', null=True),
        ),
        migrations.AddField(
            model_name='columndefinition',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Minimum value for numeric types', null=True),
        ),
        migrations.AddField(
            model_name='columndefinition',
            name='validation_regex',
            field=models.CharField(blank=True, help_text='Regular expression for validating string values', max_length=500),
        ),
    ]
