# Generated by Django 5.1.5 on 2025-03-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_columndefinition_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
    ]
