# Generated by Django 5.1.5 on 2025-03-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pdfdocument_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='processing_details',
            field=models.TextField(blank=True, help_text='Additional processing details or progress information', null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='is_complete',
            field=models.BooleanField(default=True, help_text='Whether this result contains the complete output or was truncated'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending_continuation', 'Pending Continuation'), ('pending_continuation_with_errors', 'Pending Continuation With Errors'), ('completed_with_errors', 'Completed With Errors')], default='pending', max_length=35),
        ),
    ]
