# Generated by Django 5.1.5 on 2025-03-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_processingjob_processing_details_and_more'),
    ]

    operations = [
        # No operations needed
    ]
