# Generated by Django 5.1.5 on 2025-03-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20250331_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
