# Generated by Django 5.1.4 on 2025-03-31 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_auto_20250331_1549"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processingjob",
            options={},
        ),
        migrations.AlterModelOptions(
            name="processingresult",
            options={"ordering": ["continuation_number"]},
        ),
        migrations.RemoveIndex(
            model_name="processingjob",
            name="core_proces_status_c7a5c5_idx",
        ),
        migrations.RemoveField(
            model_name="pdfdocument",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="pdfdocument",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="processingresult",
            name="raw_response",
        ),
        migrations.RemoveField(
            model_name="processingresult",
            name="result_data",
        ),
        migrations.RemoveField(
            model_name="processingresult",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="filename",
            field=models.CharField(
                blank=True, default="unnamed.pdf", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="processingresult",
            name="continuation_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processingresult",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingresult",
            name="json_result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingresult",
            name="raw_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="columndefinition",
            name="category",
            field=models.CharField(
                choices=[
                    ("demographics", "Demographics"),
                    ("clinical", "Clinical"),
                    ("pathology", "Pathology"),
                    ("treatment", "Treatment"),
                    ("outcome", "Outcome"),
                    ("presentation", "Presentation"),
                    ("symptoms", "Signs and Symptoms"),
                    ("imaging", "Imaging"),
                    ("workup", "Workup"),
                    ("intervention", "Intervention"),
                    ("postop", "Immediate Post-op Outcomes"),
                    ("followup", "Follow-up"),
                    ("lastfollowup", "Last Follow-up"),
                ],
                default="demographics",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="processingresult",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="core.pdfdocument",
            ),
        ),
        migrations.AlterField(
            model_name="processingresult",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="processingresult",
            name="is_complete",
            field=models.BooleanField(default=True),
        ),
    ]
