# Generated by Django 5.1.4 on 2025-04-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_processingjob_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="study_author",
            field=models.CharField(
                blank=True,
                help_text="Author or source of the study",
                max_length=255,
                null=True,
            ),
        ),
    ]
