# Generated by Django 5.1.4 on 2025-04-06 23:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_pdfdocument_study_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name for this case report", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_age", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "patient_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "suspected_condition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("key_findings_summary", models.TextField(blank=True, null=True)),
                ("additional_instructions", models.TextField(blank=True, null=True)),
                (
                    "patient_history_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="case_reports/patient_history/"
                    ),
                ),
                (
                    "clinical_findings_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="case_reports/clinical_findings/",
                    ),
                ),
                (
                    "lab_results_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="case_reports/lab_results/"
                    ),
                ),
                (
                    "imaging_reports_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="case_reports/imaging_reports/"
                    ),
                ),
                (
                    "treatment_summary_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="case_reports/treatment_summary/",
                    ),
                ),
                (
                    "research_prompt",
                    models.TextField(
                        blank=True,
                        help_text="The prompt sent to the research model",
                        null=True,
                    ),
                ),
                (
                    "research_response",
                    models.TextField(
                        blank=True,
                        help_text="The response from the research model",
                        null=True,
                    ),
                ),
                (
                    "draft_prompt",
                    models.TextField(
                        blank=True,
                        help_text="The prompt sent to the drafting model",
                        null=True,
                    ),
                ),
                (
                    "draft_response",
                    models.TextField(
                        blank=True,
                        help_text="The draft case report generated by the AI",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("researching", "Researching"),
                            ("drafting", "Drafting"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Case Report",
                "verbose_name_plural": "Case Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
