# Generated by Django 5.2 on 2025-04-21 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_casereport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("case_extraction", "Case Extraction"),
                    ("reference_extraction", "Reference Extraction"),
                ],
                default="case_extraction",
                help_text="The type of processing performed by this job.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "citation_text",
                    models.TextField(
                        blank=True, help_text="The full citation text as extracted."
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("journal", "Journal Article"),
                            ("book", "Book/Book Chapter"),
                            ("website", "Website/Webpage"),
                            ("report", "Report"),
                            ("conference", "Conference Proceeding"),
                            ("thesis", "Thesis/Dissertation"),
                            ("news", "News Article"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "authors",
                    models.TextField(
                        blank=True,
                        help_text="List of authors (e.g., stored as comma-separated string or JSON list)",
                        null=True,
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        help_text="Journal name, book title, website name, etc.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("volume", models.CharField(blank=True, max_length=50, null=True)),
                ("issue", models.CharField(blank=True, max_length=50, null=True)),
                ("pages", models.CharField(blank=True, max_length=50, null=True)),
                ("doi_or_url", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "confidence",
                    models.IntegerField(
                        blank=True,
                        help_text="Overall confidence score (0-100) for the parsed reference fields.",
                        null=True,
                    ),
                ),
                (
                    "raw_response_part",
                    models.TextField(
                        blank=True,
                        help_text="The specific part of the LLM's raw response that generated this reference.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="core.pdfdocument",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="core.processingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "created_at"],
                "indexes": [
                    models.Index(fields=["job"], name="core_refere_job_id_336cec_idx"),
                    models.Index(
                        fields=["document"], name="core_refere_documen_8c5d04_idx"
                    ),
                ],
            },
        ),
    ]
