# Generated by Django 5.2 on 2025-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_processingjob_job_type_processingjob_user_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="last_successful_reference_index",
            field=models.IntegerField(
                default=0,
                help_text="Index of the last successfully extracted and saved reference (0-based).",
            ),
        ),
    ]
