# Generated by Django 5.2 on 2025-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_pdfdocument_last_successful_reference_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="reference_index",
            field=models.IntegerField(
                blank=True,
                help_text="1-based index of the reference within its document",
                null=True,
            ),
        ),
    ]
